### ISSUE TITLE
コメントのキラキラ

### ISSUE THREAD

**Issue by nagiconection** [denpadokei/PokemonApp#1]
失礼します。  
現在コメントのラインが

> //ﾟ+｡*ﾟ+｡｡+ﾟ*｡+ﾟ ﾟ+｡*ﾟ+｡｡+ﾟ*｡+ﾟ ﾟ+｡*ﾟ+｡*ﾟ+｡｡+ﾟ*｡+ﾟ ﾟ+｡*ﾟ+｡｡+ﾟ*｡+ﾟ ﾟ+｡*ﾟ+｡*ﾟ+｡｡+ﾟ*｡+ﾟ ﾟ+｡*ﾟ+｡｡+ﾟ*｡+ﾟ ﾟ+｡*

となっています。  これは女子力が高くて非常に良いと思うのですが、
逆に男子力が低下しすぎている問題が発生していると思われます。
そこで

> ◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆

これにすることを提案します。

**Comment by denpadokei** [comment]
残念ながら開発者のモチベーションに直結するためこのままいかせてもらいます。
